In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
data = pd.read_csv('data_pca_1000x51.csv')

In [4]:
data.head()

                                                                                                                                                                                                                                                                                                                                x1;"x2";"x3";"x4";"x5";"x6";"x7";"x8";"x9";"x10";"x11";"x12";"x13";"x14";"x15";"x16";"x17";"x18";"x19";"x20";"x21";"x22";"x23";"x24";"x25";"x26";"x27";"x28";"x29";"x30";"x31";"x32";"x33";"x34";"x35";"x36";"x37";"x38";"x39";"x40";"x41";"x42";"x43";"x44";"x45";"x46";"x47";"x48";"x49";"x50";"y"
4  33;-1 73;0 47;-9 52;3  21;0  74;22 71;-2 01;16  16;16 66;-12 5;-21  32;4  49;-16 76;-5 92;3  8;5   69;7  6;21     16;23 65;0  2;2    22;-11 51;-1 44;-2  89;-19 75;-2 16;-17 17;-7 17;-3 69;-7 65;12 38;-0 67;-0 99;-2 96;-0 83;8  05;-8  95;6      9;-20 95;6  59;12 31;3  61;-6 57;-10 73;8  77;-0 25;-0 66;0  5;-2 16;-0                                               31.0
9  01;-1 25;0 54;-2 87;1  54;9  06;16 62;3  2;0    62;-1 94;-14 68;-14 68;-4 36;-7  99;-3 27;-3 23;-1 42;2  14;12    18;23 01;8  28;-1  91;-15 29;-5 99;-0  24;-8  48;-0 49;-19 06;1  09;5  67;19 33;11 28;5  51;-0 56;2  24;3  89;-1 06;1   56;-11;-5 45;-0 24;-3 46;5  51;-0 29;2  11;2   26;-8 23;-1 28;-4 93;4  54;1 22                                                   NaN
1  5;0   93;1 08;1  58;-9 84;-1 27;11 91;-2 91;-11 43;7  24;-9  97;1   71;7  57;6   78;-2 52;1  22;2  77;-0 43;5     95;18 49;2  79;3   7;-2   46;-1 42;-0  63;-10 64;-3 34;7   87;4  28;2  37;0  87;6  24;1  86;1  24;-3 15;3  01;10 07;6   54;-7     3;-11 03;0  58;8  75;-0 36;1  54;-3  68;7  67;-0 34;0  54;-2 26;2 86;3                                                43.0
12 21;2  87;4 6;-9  51;-3 72;6  89;26 02;7  49;2   62;5  1;-30  87;-25 09;-0 67;-4  88;-3 28;-0 33;-4 94;9  63;24;36 91;11 85;-1 05;-16 58;-8  01;-8 92;-11 68;0   6;-25 02;10  25;5  56;31 17;17 79;9  17;0  34;3  68;11 21;10 02;-7 59;-21 44;-9     12;1  61;-4 76;8  51;-5 88;3  2;2    28;-8 47;-3 99;-2 91;8  62;3 61                                                   NaN
0  37;-0 47;2 66;-7 9;1   82;1  12;20 53;2  8;18   65;9  9;-15  29;-25 19;0  06;-14 94;-1 42;-3 62;2  03;3  67;19    62;16 57;-0 96;2   34;-6  29;-4 54;-3  31;-3  47;2  64;-19 46;1  16;-0 47;-0 48;-0 6;-0  78;-1 45;1  03;1  71;6  55;-11 71;-3     72;-5 48;3  39;-0 38;0  16;-0 55;-2  94;4  5;0   13;3  22;0  71;1 68;-0                                               44.0

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1000 entries, ('4', '33;-1', '73;0', '47;-9', '52;3', '21;0', '74;22', '71;-2', '01;16', '16;16', '66;-12', '5;-21', '32;4', '49;-16', '76;-5', '92;3', '8;5', '69;7', '6;21', '16;23', '65;0', '2;2', '22;-11', '51;-1', '44;-2', '89;-19', '75;-2', '16;-17', '17;-7', '17;-3', '69;-7', '65;12', '38;-0', '67;-0', '99;-2', '96;-0', '83;8', '05;-8', '95;6', '9;-20', '95;6', '59;12', '31;3', '61;-6', '57;-10', '73;8', '77;-0', '25;-0', '66;0', '5;-2', '16;-0') to ('5', '7;-0', '97;1', '65;4;-0', '56;-7', '36;8', '35;2', '63;2', '17;6', '15;3', '13;-12', '34;8', '31;-5', '69;1', '9;-7', '77;4', '12;5', '91;3', '78;7', '64;-1', '13;3', '61;-4', '37;-3', '11;4', '2;-4', '32;-1', '87;1', '11;3', '97;0', '1;8', '8;5', '33;3', '55;-0', '79;1', '66;2', '63;7', '85;-3', '95;-2', '99;-6', '41;3', '51;-0', '12;6', '81;1', '43;-1', '21;6', '38;-7', '54;2', '95;-1', '1;1', '55;3', '69')
Data columns (total 1 columns):
 #   Column                                                                                                                                                                                                                                                                                                Non-Null Count  Dtype
---  ------                                                                                                                                                                                                                                                                                                --------------  -----
 0   x1;"x2";"x3";"x4";"x5";"x6";"x7";"x8";"x9";"x10";"x11";"x12";"x13";"x14";"x15";"x16";"x17";"x18";"x19";"x20";"x21";"x22";"x23";"x24";"x25";"x26";"x27";"x28";"x29";"x30";"x31";"x32";"x33";"x34";"x35";"x36";"x37";"x38";"x39";"x40";"x41";"x42";"x43";"x44";"x45";"x46";"x47";"x48";"x49";"x50";"y"  613 non-null    float64
dtypes: float64(1)
memory usage: 1.5+ MB

In [8]:
data.columns

Index(['x1;"x2";"x3";"x4";"x5";"x6";"x7";"x8";"x9";"x10";"x11";"x12";"x13";"x14";"x15";"x16";"x17";"x18";"x19";"x20";"x21";"x22";"x23";"x24";"x25";"x26";"x27";"x28";"x29";"x30";"x31";"x32";"x33";"x34";"x35";"x36";"x37";"x38";"x39";"x40";"x41";"x42";"x43";"x44";"x45";"x46";"x47";"x48";"x49";"x50";"y"'], dtype='object')

In [13]:
data['x1;"x2";"x3";"x4";"x5";"x6";"x7";"x8";"x9";"x10";"x11";"x12";"x13";"x14";"x15";"x16";"x17";"x18";"x19";"x20";"x21";"x22";"x23";"x24";"x25";"x26";"x27";"x28";"x29";"x30";"x31";"x32";"x33";"x34";"x35";"x36";"x37";"x38";"x39";"x40";"x41";"x42";"x43";"x44";"x45";"x46";"x47";"x48";"x49";"x50";"y"']

4   33;-1  73;0   47;-9    52;3   21;0   74;22  71;-2  01;16   16;16  66;-12  5;-21   32;4   49;-16  76;-5  92;3    8;5    69;7   6;21      16;23  65;0   2;2     22;-11  51;-1  44;-2   89;-19  75;-2  16;-17  17;-7  17;-3  69;-7  65;12  38;-0  67;-0  99;-2  96;-0  83;8   05;-8   95;6       9;-20   95;6   59;12   31;3   61;-6   57;-10  73;8   77;-0  25;-0  66;0   5;-2  16;-0    31.0
9   01;-1  25;0   54;-2    87;1   54;9   06;16  62;3   2;0     62;-1  94;-14  68;-14  68;-4  36;-7   99;-3  27;-3   23;-1  42;2   14;12     18;23  01;8   28;-1   91;-15  29;-5  99;-0   24;-8   48;-0  49;-19  06;1   09;5   67;19  33;11  28;5   51;-0  56;2   24;3   89;-1  06;1    56;-11;-5  45;-0   24;-3  46;5    51;-0  29;2    11;2    26;-8  23;-1  28;-4  93;4   54;1  22        NaN
1   5;0    93;1   08;1     58;-9  84;-1  27;11  91;-2  91;-11  43;7   24;-9   97;1    71;7   57;6    78;-2  52;1    22;2   77;-0  43;5      95;18  49;2   79;3    7;-2    46;-1  42;-0   63;-10  64;-3  34;7    87;4   28;2   37;0   87;6   24;1   86;1   24;-3  15;3   01;10  07;6    54;-7      3;-11   03;0   58;8    75;-0  36;1    54;-3   68;7   67;-0  34;0   54;-2  26;2  86;3     43.0
12  21;2   87;4   6;-9     51;-3  72;6   89;26  02;7   49;2    62;5   1;-30   87;-25  09;-0  67;-4   88;-3  28;-0   33;-4  94;9   63;24;36  91;11  85;-1  05;-16  58;-8   01;-8  92;-11  68;0    6;-25  02;10   25;5   56;31  17;17  79;9   17;0   34;3   68;11  21;10  02;-7  59;-21  44;-9      12;1    61;-4  76;8    51;-5  88;3    2;2     28;-8  47;-3  99;-2  91;8   62;3  61        NaN
0   37;-0  47;2   66;-7    9;1    82;1   12;20  53;2   8;18    65;9   9;-15   29;-25  19;0   06;-14  94;-1  42;-3   62;2   03;3   67;19     62;16  57;-0  96;2    34;-6   29;-4  54;-3   31;-3   47;2   64;-19  46;1   16;-0  47;-0  48;-0  6;-0   78;-1  45;1   03;1   71;6   55;-11  71;-3      72;-5   48;3   39;-0   38;0   16;-0   55;-2   94;4   5;0    13;3   22;0   71;1  68;-0    44.0
                                                                                                                                                                                                                                                                                                                                                                                           ...
10  13;0   23;5   06;0     09;0   34;-4  52;12  13;0   97;-3   66;14  91;-8   68;-19  19;-1  93;-3   8;-4   72;15   18;6   11;5   4;2       92;17  49;2   8;-2    09;-10  96;-8  77;1    73;-14  48;6   25;-19  61;4   69;-8  67;15  33;3   34;-5  92;0   9;1    6;4    2;4    19;-2   73;-12     7;-22   32;0   13;13   09;-2  25;-14  71;-3   71;9   52;1   42;4   05;3   86;7  31;0     17.0
7   85;0   75;-1  67;-11   43;2   79;7   14;25  1;4    33;10   66;8   31;-19  13;-28  5;-1   83;-13  28;-2  85;-1   12;5   36;5   25;20     11;29  73;1   45;4    32;-20  09;-4  12;-8   74;-11  03;-0  96;-28  09;-2  37;-3  89;-0  59;4   8;-2   41;0   2;0    31;-1  47;4   6;-4    93;-0      5;-13   46;-2  05;2    69;1   89;-1   95;-3   38;8   75;-1  84;3   92;-2  28;2  42;-2    73.0
-8  23;1   09;4   23;-0    68;4   05;-4  1;6    24;7   26;2    79;-0  57;-1   24;-9   57;7   95;-3   28;-4  12;-14  31;-6  54;-2  39;-0     92;3   74;0   06;0    43;7    09;-6  48;-3   95;-4   22;3   19;6    99;5   24;9   77;14  13;11  63;7   23;-1  7;3    75;4   14;5   23;-5   18;-9      38;3    68;2   67;-12  28;2   15;5    79;4    64;0   04;1   26;-0  89;-7  68;4  41;1     69.0
8   58;6   26;-4  3;-1     35;0   76;0   36;18  59;-3  07;3    49;5   97;-12  35;-24  45;-3  19;-13  32;-0  8;1     1;6    11;2   87;12     47;21  19;3   49;3    11;-17  31;-3  01;1    52;-6   65;-0  68;-23  34;-2  43;-2  94;-2  2;-4   63;-7  29;-1  41;-3  97;1   94;1   83;-3   09;-2      88;-13  98;-0  55;7    65;-2  43;-0   93;-7   92;9   18;8   41;6   56;0   15;3  95;-2    15.0
5   7;-0   97;1   65;4;-0  56;-7  36;8   35;2   63;2   17;6    15;3   13;-12  34;8    31;-5  69;1    9;-7   77;4    12;5   91;3   78;7      64;-1  13;3   61;-4   37;-3   11;4   2;-4    32;-1   87;1   11;3    97;0   1;8    8;5    33;3   55;-0  79;1   66;2   63;7   85;-3  95;-2   99;-6      41;3    51;-0  12;6    81;1   43;-1   21;6    38;-7  54;2   95;-1  1;1    55;3  69        NaN
Name: x1;"x2";"x3";"x4";"x5";"x6";"x7";"x8";"x9";"x10";"x11";"x12";"x13";"x14";"x15";"x16";"x17";"x18";"x19";"x20";"x21";"x22";"x23";"x24";"x25";"x26";"x27";"x28";"x29";"x30";"x31";"x32";"x33";"x34";"x35";"x36";"x37";"x38";"x39";"x40";"x41";"x42";"x43";"x44";"x45";"x46";"x47";"x48";"x49";"x50";"y", Length: 1000, dtype: float64

In [14]:
data = data.reset_index()

In [15]:
data.head()

,level_0,level_1,level_2,level_3,level_4,level_5,level_6,level_7,level_8,level_9,...,level_42,level_43,level_44,level_45,level_46,level_47,level_48,level_49,level_50,"x1;""x2"";""x3"";""x4"";""x5"";""x6"";""x7"";""x8"";""x9"";""x10"";""x11"";""x12"";""x13"";""x14"";""x15"";""x16"";""x17"";""x18"";""x19"";""x20"";""x21"";""x22"";""x23"";""x24"";""x25"";""x26"";""x27"";""x28"";""x29"";""x30"";""x31"";""x32"";""x33"";""x34"";""x35"";""x36"";""x37"";""x38"";""x39"";""x40"";""x41"";""x42"";""x43"";""x44"";""x45"";""x46"";""x47"";""x48"";""x49"";""x50"";""y"""
0,4,33;-1,73;0,47;-9,52;3,21;0,74;22,71;-2,01;16,16;16,...,31;3,61;-6,57;-10,73;8,77;-0,25;-0,66;0,5;-2,16;-0,31.0
1,9,01;-1,25;0,54;-2,87;1,54;9,06;16,62;3,2;0,62;-1,...,51;-0,29;2,11;2,26;-8,23;-1,28;-4,93;4,54;1,22,NaN
2,1,5;0,93;1,08;1,58;-9,84;-1,27;11,91;-2,91;-11,43;7,...,75;-0,36;1,54;-3,68;7,67;-0,34;0,54;-2,26;2,86;3,43.0
3,12,21;2,87;4,6;-9,51;-3,72;6,89;26,02;7,49;2,62;5,...,51;-5,88;3,2;2,28;-8,47;-3,99;-2,91;8,62;3,61,NaN
4,0,37;-0,47;2,66;-7,9;1,82;1,12;20,53;2,8;18,65;9,...,38;0,16;-0,55;-2,94;4,5;0,13;3,22;0,71;1,68;-0,44.0

In [16]:
data['level_0']

0       4
1       9
2       1
3      12
4       0
       ..
995    10
996     7
997    -8
998     8
999     5
Name: level_0, Length: 1000, dtype: object

In [18]:
df

,level_0,level_1,level_2,level_3,level_4,level_5,level_6,level_7,level_8,level_9,...,level_42,level_43,level_44,level_45,level_46,level_47,level_48,level_49,level_50,"x1;""x2"";""x3"";""x4"";""x5"";""x6"";""x7"";""x8"";""x9"";""x10"";""x11"";""x12"";""x13"";""x14"";""x15"";""x16"";""x17"";""x18"";""x19"";""x20"";""x21"";""x22"";""x23"";""x24"";""x25"";""x26"";""x27"";""x28"";""x29"";""x30"";""x31"";""x32"";""x33"";""x34"";""x35"";""x36"";""x37"";""x38"";""x39"";""x40"";""x41"";""x42"";""x43"";""x44"";""x45"";""x46"";""x47"";""x48"";""x49"";""x50"";""y"""
0,4,33;-1,73;0,47;-9,52;3,21;0,74;22,71;-2,01;16,16;16,...,31;3,61;-6,57;-10,73;8,77;-0,25;-0,66;0,5;-2,16;-0,31.0
1,9,01;-1,25;0,54;-2,87;1,54;9,06;16,62;3,2;0,62;-1,...,51;-0,29;2,11;2,26;-8,23;-1,28;-4,93;4,54;1,22,NaN
2,1,5;0,93;1,08;1,58;-9,84;-1,27;11,91;-2,91;-11,43;7,...,75;-0,36;1,54;-3,68;7,67;-0,34;0,54;-2,26;2,86;3,43.0
3,12,21;2,87;4,6;-9,51;-3,72;6,89;26,02;7,49;2,62;5,...,51;-5,88;3,2;2,28;-8,47;-3,99;-2,91;8,62;3,61,NaN
4,0,37;-0,47;2,66;-7,9;1,82;1,12;20,53;2,8;18,65;9,...,38;0,16;-0,55;-2,94;4,5;0,13;3,22;0,71;1,68;-0,44.0
5,5,01;1,18;-1,78;4,77;-2,06;1,34;6,02;4,75;-4,77;-4,...,05;11,68;-1,34;5,97;1,31;-13,72;-6,15;-2,02;-3,46;2,61.0
6,8,75;7,17;-8,4;-5,98;0,96;-2,91;7,82;-5,33;2,58;12,...,64;-16,33;-0,62;-6,43;9,97;16,17;4,49;0,34;0,96;-1,55.0
7,1,33;5,44;-4,34;-12,8;4,12;4,45;21,64;-0,73;14,81;-3,...,98;-1,17;7,43;5,41;6,89;5,3;-1,3;-2,58;-0,02;1,2.0
8,3,95;4,59;-4,55;8,88;-2,24;-8,18;8,13;1,33;-1,15;6,...,38;3,45;-2,83;-3,52;8,66;0,26;3;0,81;-0,11;1,45,NaN
9,-4,19;4,86;-2,06;6,08;4,42;0,87;-1,14;-5,87;-9,08;4,...,37;4,66;-1,54;7,73;-3,45;-0,25;0,13;4,84;0,51,NaN

In [22]:
data.shape

(1000, 52)

In [26]:
data.iloc[300]

level_0                                                                                                                                                                                                                                                                                                      13
level_1                                                                                                                                                                                                                                                                                                    75;1
level_2                                                                                                                                                                                                                                                                                                    89;6
level_3                                                                                                                                                                                                                                                                                                  04;-17
level_4                                                                                                                                                                                                                                                                                                   57;-3
level_5                                                                                                                                                                                                                                                                                                   32;-0
level_6                                                                                                                                                                                                                                                                                                   53;27
level_7                                                                                                                                                                                                                                                                                                    26;7
level_8                                                                                                                                                                                                                                                                                                    1;10
level_9                                                                                                                                                                                                                                                                                                    89;0
level_10                                                                                                                                                                                                                                                                                                 63;-31
level_11                                                                                                                                                                                                                                                                                                 38;-27
level_12                                                                                                                                                                                                                                                                                                  88;-5
level_13                                                                                                                                                                                                                                                                                                  28;-5
level_14                                                                                                                                                                                                                                                                                                  06;-5
level_15                                                                                                                                                                                                                                                                                                  42;-1
level_16                                                                                                                                                                                                                                                                                                  97;-2
level_17                                                                                                                                                                                                                                                                                                  64;11
level_18                                                                                                                                                                                                                                                                                                  31;29
level_19                                                                                                                                                                                                                                                                                                  77;31
level_20                                                                                                                                                                                                                                                                                                    8;0
level_21                                                                                                                                                                                                                                                                                                   79;0
level_22                                                                                                                                                                                                                                                                                                  08;-9
level_23                                                                                                                                                                                                                                                                                                 67;-10
level_24                                                                                                                                                                                                                                                                                                  68;-4
level_25                                                                                                                                                                                                                                                                                                  22;-7
level_26                                                                                                                                                                                                                                                                                                   27;8
level_27                                                                                                                                                                                                                                                                                                 27;-28
level_28                                                                                                                                                                                                                                                                                                   95;7
level_29                                                                                                                                                                                                                                                                                                   64;4
level_30                                                                                                                                                                                                                                                                                                  68;16
level_31                                                                                                                                                                                                                                                                                                  81;16
level_32                                                                                                                                                                                                                                                                                                   81;7
level_33                                                                                                                                                                                                                                                                                                  15;-4
level_34                                                                                                                                                                                                                                                                                                   36;6
level_35                                                                                                                                                                                                                                                                                                   79;4
level_36                                                                                                                                                                                                                                                                                                  65;12
level_37                                                                                                                                                                                                                                                                                                  35;-7
level_38                                                                                                                                                                                                                                                                                                 15;-13
level_39                                                                                                                                                                                                                                                                                                  96;-4
level_40                                                                                                                                                                                                                                                                                                   66;3
level_41                                                                                                                                                                                                                                                                                                 59;-14
level_42                                                                                                                                                                                                                                                                                                  46;-2
level_43                                                                                                                                                                                                                                                                                                  72;-7
level_44                                                                                                                                                                                                                                                                                                   28;3
level_45                                                                                                                                                                                                                                                                                                   7;-0
level_46                                                                                                                                                                                                                                                                                                58;7;-2
level_47                                                                                                                                                                                                                                                                                                  66;-3
level_48                                                                                                                                                                                                                                                                                                   93;8
level_49                                                                                                                                                                                                                                                                                                   83;1
level_50                                                                                                                                                                                                                                                                                                     97
x1;"x2";"x3";"x4";"x5";"x6";"x7";"x8";"x9";"x10";"x11";"x12";"x13";"x14";"x15";"x16";"x17";"x18";"x19";"x20";"x21";"x22";"x23";"x24";"x25";"x26";"x27";"x28";"x29";"x30";"x31";"x32";"x33";"x34";"x35";"x36";"x37";"x38";"x39";"x40";"x41";"x42";"x43";"x44";"x45";"x46";"x47";"x48";"x49";"x50";"y"        NaN
Name: 300, dtype: object

In [30]:
l = data['x1;"x2";"x3";"x4";"x5";"x6";"x7";"x8";"x9";"x10";"x11";"x12";"x13";"x14";"x15";"x16";"x17";"x18";"x19";"x20";"x21";"x22";"x23";"x24";"x25";"x26";"x27";"x28";"x29";"x30";"x31";"x32";"x33";"x34";"x35";"x36";"x37";"x38";"x39";"x40";"x41";"x42";"x43";"x44";"x45";"x46";"x47";"x48";"x49";"x50";"y"']

In [31]:
l

0      31.0
1       NaN
2      43.0
3       NaN
4      44.0
       ...
995    17.0
996    73.0
997    69.0
998    15.0
999     NaN
Name: x1;"x2";"x3";"x4";"x5";"x6";"x7";"x8";"x9";"x10";"x11";"x12";"x13";"x14";"x15";"x16";"x17";"x18";"x19";"x20";"x21";"x22";"x23";"x24";"x25";"x26";"x27";"x28";"x29";"x30";"x31";"x32";"x33";"x34";"x35";"x36";"x37";"x38";"x39";"x40";"x41";"x42";"x43";"x44";"x45";"x46";"x47";"x48";"x49";"x50";"y", Length: 1000, dtype: float64

In [34]:
new_df = data.drop(columns = 'x1;"x2";"x3";"x4";"x5";"x6";"x7";"x8";"x9";"x10";"x11";"x12";"x13";"x14";"x15";"x16";"x17";"x18";"x19";"x20";"x21";"x22";"x23";"x24";"x25";"x26";"x27";"x28";"x29";"x30";"x31";"x32";"x33";"x34";"x35";"x36";"x37";"x38";"x39";"x40";"x41";"x42";"x43";"x44";"x45";"x46";"x47";"x48";"x49";"x50";"y"')

In [35]:
new_df

,level_0,level_1,level_2,level_3,level_4,level_5,level_6,level_7,level_8,level_9,...,level_41,level_42,level_43,level_44,level_45,level_46,level_47,level_48,level_49,level_50
0,4,33;-1,73;0,47;-9,52;3,21;0,74;22,71;-2,01;16,16;16,...,59;12,31;3,61;-6,57;-10,73;8,77;-0,25;-0,66;0,5;-2,16;-0
1,9,01;-1,25;0,54;-2,87;1,54;9,06;16,62;3,2;0,62;-1,...,46;5,51;-0,29;2,11;2,26;-8,23;-1,28;-4,93;4,54;1,22
2,1,5;0,93;1,08;1,58;-9,84;-1,27;11,91;-2,91;-11,43;7,...,58;8,75;-0,36;1,54;-3,68;7,67;-0,34;0,54;-2,26;2,86;3
3,12,21;2,87;4,6;-9,51;-3,72;6,89;26,02;7,49;2,62;5,...,76;8,51;-5,88;3,2;2,28;-8,47;-3,99;-2,91;8,62;3,61
4,0,37;-0,47;2,66;-7,9;1,82;1,12;20,53;2,8;18,65;9,...,39;-0,38;0,16;-0,55;-2,94;4,5;0,13;3,22;0,71;1,68;-0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,10,13;0,23;5,06;0,09;0,34;-4,52;12,13;0,97;-3,66;14,...,13;13,09;-2,25;-14,71;-3,71;9,52;1,42;4,05;3,86;7,31;0
996,7,85;0,75;-1,67;-11,43;2,79;7,14;25,1;4,33;10,66;8,...,05;2,69;1,89;-1,95;-3,38;8,75;-1,84;3,92;-2,28;2,42;-2
997,-8,23;1,09;4,23;-0,68;4,05;-4,1;6,24;7,26;2,79;-0,...,67;-12,28;2,15;5,79;4,64;0,04;1,26;-0,89;-7,68;4,41;1
998,8,58;6,26;-4,3;-1,35;0,76;0,36;18,59;-3,07;3,49;5,...,55;7,65;-2,43;-0,93;-7,92;9,18;8,41;6,56;0,15;3,95;-2
999,5,7;-0,97;1,65;4;-0,56;-7,36;8,35;2,63;2,17;6,15;3,...,12;6,81;1,43;-1,21;6,38;-7,54;2,95;-1,1;1,55;3,69

In [38]:
df

,level_0,level_1,level_2,level_3,level_4,level_5,level_6,level_7,level_8,level_9,...,level_42,level_43,level_44,level_45,level_46,level_47,level_48,level_49,level_50,target
0,4,33;-1,73;0,47;-9,52;3,21;0,74;22,71;-2,01;16,16;16,...,31;3,61;-6,57;-10,73;8,77;-0,25;-0,66;0,5;-2,16;-0,31.0
1,9,01;-1,25;0,54;-2,87;1,54;9,06;16,62;3,2;0,62;-1,...,51;-0,29;2,11;2,26;-8,23;-1,28;-4,93;4,54;1,22,NaN
2,1,5;0,93;1,08;1,58;-9,84;-1,27;11,91;-2,91;-11,43;7,...,75;-0,36;1,54;-3,68;7,67;-0,34;0,54;-2,26;2,86;3,43.0
3,12,21;2,87;4,6;-9,51;-3,72;6,89;26,02;7,49;2,62;5,...,51;-5,88;3,2;2,28;-8,47;-3,99;-2,91;8,62;3,61,NaN
4,0,37;-0,47;2,66;-7,9;1,82;1,12;20,53;2,8;18,65;9,...,38;0,16;-0,55;-2,94;4,5;0,13;3,22;0,71;1,68;-0,44.0
5,5,01;1,18;-1,78;4,77;-2,06;1,34;6,02;4,75;-4,77;-4,...,05;11,68;-1,34;5,97;1,31;-13,72;-6,15;-2,02;-3,46;2,61.0
6,8,75;7,17;-8,4;-5,98;0,96;-2,91;7,82;-5,33;2,58;12,...,64;-16,33;-0,62;-6,43;9,97;16,17;4,49;0,34;0,96;-1,55.0
7,1,33;5,44;-4,34;-12,8;4,12;4,45;21,64;-0,73;14,81;-3,...,98;-1,17;7,43;5,41;6,89;5,3;-1,3;-2,58;-0,02;1,2.0
8,3,95;4,59;-4,55;8,88;-2,24;-8,18;8,13;1,33;-1,15;6,...,38;3,45;-2,83;-3,52;8,66;0,26;3;0,81;-0,11;1,45,NaN
9,-4,19;4,86;-2,06;6,08;4,42;0,87;-1,14;-5,87;-9,08;4,...,37;4,66;-1,54;7,73;-3,45;-0,25;0,13;4,84;0,51,NaN

In [39]:
new_df['target'] = l

In [40]:
new_df

,level_0,level_1,level_2,level_3,level_4,level_5,level_6,level_7,level_8,level_9,...,level_42,level_43,level_44,level_45,level_46,level_47,level_48,level_49,level_50,target
0,4,33;-1,73;0,47;-9,52;3,21;0,74;22,71;-2,01;16,16;16,...,31;3,61;-6,57;-10,73;8,77;-0,25;-0,66;0,5;-2,16;-0,31.0
1,9,01;-1,25;0,54;-2,87;1,54;9,06;16,62;3,2;0,62;-1,...,51;-0,29;2,11;2,26;-8,23;-1,28;-4,93;4,54;1,22,NaN
2,1,5;0,93;1,08;1,58;-9,84;-1,27;11,91;-2,91;-11,43;7,...,75;-0,36;1,54;-3,68;7,67;-0,34;0,54;-2,26;2,86;3,43.0
3,12,21;2,87;4,6;-9,51;-3,72;6,89;26,02;7,49;2,62;5,...,51;-5,88;3,2;2,28;-8,47;-3,99;-2,91;8,62;3,61,NaN
4,0,37;-0,47;2,66;-7,9;1,82;1,12;20,53;2,8;18,65;9,...,38;0,16;-0,55;-2,94;4,5;0,13;3,22;0,71;1,68;-0,44.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,10,13;0,23;5,06;0,09;0,34;-4,52;12,13;0,97;-3,66;14,...,09;-2,25;-14,71;-3,71;9,52;1,42;4,05;3,86;7,31;0,17.0
996,7,85;0,75;-1,67;-11,43;2,79;7,14;25,1;4,33;10,66;8,...,69;1,89;-1,95;-3,38;8,75;-1,84;3,92;-2,28;2,42;-2,73.0
997,-8,23;1,09;4,23;-0,68;4,05;-4,1;6,24;7,26;2,79;-0,...,28;2,15;5,79;4,64;0,04;1,26;-0,89;-7,68;4,41;1,69.0
998,8,58;6,26;-4,3;-1,35;0,76;0,36;18,59;-3,07;3,49;5,...,65;-2,43;-0,93;-7,92;9,18;8,41;6,56;0,15;3,95;-2,15.0
999,5,7;-0,97;1,65;4;-0,56;-7,36;8,35;2,63;2,17;6,15;3,...,81;1,43;-1,21;6,38;-7,54;2,95;-1,1;1,55;3,69,NaN

In [41]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 52 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   level_0   1000 non-null   object
 1   level_1   1000 non-null   object
 2   level_2   1000 non-null   object
 3   level_3   1000 non-null   object
 4   level_4   1000 non-null   object
 5   level_5   1000 non-null   object
 6   level_6   1000 non-null   object
 7   level_7   1000 non-null   object
 8   level_8   1000 non-null   object
 9   level_9   1000 non-null   object
 10  level_10  1000 non-null   object
 11  level_11  1000 non-null   object
 12  level_12  1000 non-null   object
 13  level_13  1000 non-null   object
 14  level_14  1000 non-null   object
 15  level_15  1000 non-null   object
 16  level_16  1000 non-null   object
 17  level_17  1000 non-null   object
 18  level_18  1000 non-null   object
 19  level_19  1000 non-null   object
 20  level_20  1000 non-null   object
 21  level_21  1000 non-null   object
 22  level_22  1000 non-null   object
 23  level_23  1000 non-null   object
 24  level_24  1000 non-null   object
 25  level_25  1000 non-null   object
 26  level_26  1000 non-null   object
 27  level_27  1000 non-null   object
 28  level_28  1000 non-null   object
 29  level_29  1000 non-null   object
 30  level_30  1000 non-null   object
 31  level_31  1000 non-null   object
 32  level_32  1000 non-null   object
 33  level_33  1000 non-null   object
 34  level_34  1000 non-null   object
 35  level_35  1000 non-null   object
 36  level_36  1000 non-null   object
 37  level_37  1000 non-null   object
 38  level_38  1000 non-null   object
 39  level_39  1000 non-null   object
 40  level_40  1000 non-null   object
 41  level_41  1000 non-null   object
 42  level_42  1000 non-null   object
 43  level_43  1000 non-null   object
 44  level_44  1000 non-null   object
 45  level_45  1000 non-null   object
 46  level_46  1000 non-null   object
 47  level_47  1000 non-null   object
 48  level_48  998 non-null    object
 49  level_49  988 non-null    object
 50  level_50  925 non-null    object
 51  target    613 non-null    float64
dtypes: float64(1), object(51)
memory usage: 406.4+ KB

In [42]:
new_df.isnull().sum()

level_0       0
level_1       0
level_2       0
level_3       0
level_4       0
level_5       0
level_6       0
level_7       0
level_8       0
level_9       0
level_10      0
level_11      0
level_12      0
level_13      0
level_14      0
level_15      0
level_16      0
level_17      0
level_18      0
level_19      0
level_20      0
level_21      0
level_22      0
level_23      0
level_24      0
level_25      0
level_26      0
level_27      0
level_28      0
level_29      0
level_30      0
level_31      0
level_32      0
level_33      0
level_34      0
level_35      0
level_36      0
level_37      0
level_38      0
level_39      0
level_40      0
level_41      0
level_42      0
level_43      0
level_44      0
level_45      0
level_46      0
level_47      0
level_48      2
level_49     12
level_50     75
target      387
dtype: int64

In [43]:
new_df.dropna(inplace=True)

In [44]:
new_df.isnull().sum()

level_0     0
level_1     0
level_2     0
level_3     0
level_4     0
level_5     0
level_6     0
level_7     0
level_8     0
level_9     0
level_10    0
level_11    0
level_12    0
level_13    0
level_14    0
level_15    0
level_16    0
level_17    0
level_18    0
level_19    0
level_20    0
level_21    0
level_22    0
level_23    0
level_24    0
level_25    0
level_26    0
level_27    0
level_28    0
level_29    0
level_30    0
level_31    0
level_32    0
level_33    0
level_34    0
level_35    0
level_36    0
level_37    0
level_38    0
level_39    0
level_40    0
level_41    0
level_42    0
level_43    0
level_44    0
level_45    0
level_46    0
level_47    0
level_48    0
level_49    0
level_50    0
target      0
dtype: int64

In [59]:
j = '&-;,4'
j.split(';')

['&-', ',4']

In [64]:
def convert(obj):
    ans = 0
    for a in obj:
        if a.isdigit():
            ans = a
            break 
    return int(ans)

In [65]:
l = ['47;-9','52;3','21;0','74;22','71;-2','&-;,4']
b = []
for a in l:
    ans = convert(a)
    b.append(ans)

In [66]:
b

[4, 5, 2, 7, 7, 4]

In [68]:
df['level_0'].apply(convert)

0    4
1    9
2    1
3    1
4    0
5    5
6    8
7    1
8    3
9    4
Name: level_0, dtype: int64

In [69]:
df

,level_0,level_1,level_2,level_3,level_4,level_5,level_6,level_7,level_8,level_9,...,level_42,level_43,level_44,level_45,level_46,level_47,level_48,level_49,level_50,target
0,4,33;-1,73;0,47;-9,52;3,21;0,74;22,71;-2,01;16,16;16,...,31;3,61;-6,57;-10,73;8,77;-0,25;-0,66;0,5;-2,16;-0,31.0
1,9,01;-1,25;0,54;-2,87;1,54;9,06;16,62;3,2;0,62;-1,...,51;-0,29;2,11;2,26;-8,23;-1,28;-4,93;4,54;1,22,NaN
2,1,5;0,93;1,08;1,58;-9,84;-1,27;11,91;-2,91;-11,43;7,...,75;-0,36;1,54;-3,68;7,67;-0,34;0,54;-2,26;2,86;3,43.0
3,12,21;2,87;4,6;-9,51;-3,72;6,89;26,02;7,49;2,62;5,...,51;-5,88;3,2;2,28;-8,47;-3,99;-2,91;8,62;3,61,NaN
4,0,37;-0,47;2,66;-7,9;1,82;1,12;20,53;2,8;18,65;9,...,38;0,16;-0,55;-2,94;4,5;0,13;3,22;0,71;1,68;-0,44.0
5,5,01;1,18;-1,78;4,77;-2,06;1,34;6,02;4,75;-4,77;-4,...,05;11,68;-1,34;5,97;1,31;-13,72;-6,15;-2,02;-3,46;2,61.0
6,8,75;7,17;-8,4;-5,98;0,96;-2,91;7,82;-5,33;2,58;12,...,64;-16,33;-0,62;-6,43;9,97;16,17;4,49;0,34;0,96;-1,55.0
7,1,33;5,44;-4,34;-12,8;4,12;4,45;21,64;-0,73;14,81;-3,...,98;-1,17;7,43;5,41;6,89;5,3;-1,3;-2,58;-0,02;1,2.0
8,3,95;4,59;-4,55;8,88;-2,24;-8,18;8,13;1,33;-1,15;6,...,38;3,45;-2,83;-3,52;8,66;0,26;3;0,81;-0,11;1,45,NaN
9,-4,19;4,86;-2,06;6,08;4,42;0,87;-1,14;-5,87;-9,08;4,...,37;4,66;-1,54;7,73;-3,45;-0,25;0,13;4,84;0,51,NaN

In [75]:
l = list(df.columns)

In [76]:
l.remove('target')

In [77]:
l

['level_0',
 'level_1',
 'level_2',
 'level_3',
 'level_4',
 'level_5',
 'level_6',
 'level_7',
 'level_8',
 'level_9',
 'level_10',
 'level_11',
 'level_12',
 'level_13',
 'level_14',
 'level_15',
 'level_16',
 'level_17',
 'level_18',
 'level_19',
 'level_20',
 'level_21',
 'level_22',
 'level_23',
 'level_24',
 'level_25',
 'level_26',
 'level_27',
 'level_28',
 'level_29',
 'level_30',
 'level_31',
 'level_32',
 'level_33',
 'level_34',
 'level_35',
 'level_36',
 'level_37',
 'level_38',
 'level_39',
 'level_40',
 'level_41',
 'level_42',
 'level_43',
 'level_44',
 'level_45',
 'level_46',
 'level_47',
 'level_48',
 'level_49',
 'level_50']

In [81]:
df

,level_0,level_1,level_2,level_3,level_4,level_5,level_6,level_7,level_8,level_9,...,level_42,level_43,level_44,level_45,level_46,level_47,level_48,level_49,level_50,target
0,4,3,7,4,5,2,7,7,0,1,...,3,6,5,7,7,2,6,5,1,31.0
1,9,0,2,5,8,5,0,6,2,6,...,5,2,1,2,2,2,9,5,2,NaN
2,1,5,9,0,5,8,2,9,9,4,...,7,3,5,6,6,3,5,2,8,43.0
3,1,2,8,6,5,7,8,0,4,6,...,5,8,2,2,4,9,9,6,6,NaN
4,0,3,4,6,9,8,1,5,8,6,...,3,1,5,9,5,1,2,7,6,44.0
5,5,0,1,7,7,0,3,0,7,7,...,0,6,3,9,3,7,1,0,4,61.0
6,8,7,1,4,9,9,9,8,3,5,...,6,3,6,4,9,1,4,3,9,55.0
7,1,3,4,3,8,1,4,6,7,8,...,9,1,4,4,8,3,3,5,0,2.0
8,3,9,5,5,8,2,1,1,3,1,...,3,4,8,5,6,2,8,1,4,NaN
9,4,1,8,0,0,4,8,1,8,0,...,3,6,5,7,4,2,1,8,5,NaN

In [82]:
df.isnull().sum()

level_0     0
level_1     0
level_2     0
level_3     0
level_4     0
level_5     0
level_6     0
level_7     0
level_8     0
level_9     0
level_10    0
level_11    0
level_12    0
level_13    0
level_14    0
level_15    0
level_16    0
level_17    0
level_18    0
level_19    0
level_20    0
level_21    0
level_22    0
level_23    0
level_24    0
level_25    0
level_26    0
level_27    0
level_28    0
level_29    0
level_30    0
level_31    0
level_32    0
level_33    0
level_34    0
level_35    0
level_36    0
level_37    0
level_38    0
level_39    0
level_40    0
level_41    0
level_42    0
level_43    0
level_44    0
level_45    0
level_46    0
level_47    0
level_48    0
level_49    0
level_50    0
target      4
dtype: int64

In [83]:
for lvl in l:
    new_df[lvl] = new_df[lvl].apply(convert)

In [85]:
new_df.head()

,level_0,level_1,level_2,level_3,level_4,level_5,level_6,level_7,level_8,level_9,...,level_42,level_43,level_44,level_45,level_46,level_47,level_48,level_49,level_50,target
0,4,3,7,4,5,2,7,7,0,1,...,3,6,5,7,7,2,6,5,1,31.0
2,1,5,9,0,5,8,2,9,9,4,...,7,3,5,6,6,3,5,2,8,43.0
4,0,3,4,6,9,8,1,5,8,6,...,3,1,5,9,5,1,2,7,6,44.0
5,5,0,1,7,7,0,3,0,7,7,...,0,6,3,9,3,7,1,0,4,61.0
6,8,7,1,4,9,9,9,8,3,5,...,6,3,6,4,9,1,4,3,9,55.0

In [86]:
new_df.isnull().sum()

level_0     0
level_1     0
level_2     0
level_3     0
level_4     0
level_5     0
level_6     0
level_7     0
level_8     0
level_9     0
level_10    0
level_11    0
level_12    0
level_13    0
level_14    0
level_15    0
level_16    0
level_17    0
level_18    0
level_19    0
level_20    0
level_21    0
level_22    0
level_23    0
level_24    0
level_25    0
level_26    0
level_27    0
level_28    0
level_29    0
level_30    0
level_31    0
level_32    0
level_33    0
level_34    0
level_35    0
level_36    0
level_37    0
level_38    0
level_39    0
level_40    0
level_41    0
level_42    0
level_43    0
level_44    0
level_45    0
level_46    0
level_47    0
level_48    0
level_49    0
level_50    0
target      0
dtype: int64

In [87]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 613 entries, 0 to 998
Data columns (total 52 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   level_0   613 non-null    int64
 1   level_1   613 non-null    int64
 2   level_2   613 non-null    int64
 3   level_3   613 non-null    int64
 4   level_4   613 non-null    int64
 5   level_5   613 non-null    int64
 6   level_6   613 non-null    int64
 7   level_7   613 non-null    int64
 8   level_8   613 non-null    int64
 9   level_9   613 non-null    int64
 10  level_10  613 non-null    int64
 11  level_11  613 non-null    int64
 12  level_12  613 non-null    int64
 13  level_13  613 non-null    int64
 14  level_14  613 non-null    int64
 15  level_15  613 non-null    int64
 16  level_16  613 non-null    int64
 17  level_17  613 non-null    int64
 18  level_18  613 non-null    int64
 19  level_19  613 non-null    int64
 20  level_20  613 non-null    int64
 21  level_21  613 non-null    int64
 22  level_22  613 non-null    int64
 23  level_23  613 non-null    int64
 24  level_24  613 non-null    int64
 25  level_25  613 non-null    int64
 26  level_26  613 non-null    int64
 27  level_27  613 non-null    int64
 28  level_28  613 non-null    int64
 29  level_29  613 non-null    int64
 30  level_30  613 non-null    int64
 31  level_31  613 non-null    int64
 32  level_32  613 non-null    int64
 33  level_33  613 non-null    int64
 34  level_34  613 non-null    int64
 35  level_35  613 non-null    int64
 36  level_36  613 non-null    int64
 37  level_37  613 non-null    int64
 38  level_38  613 non-null    int64
 39  level_39  613 non-null    int64
 40  level_40  613 non-null    int64
 41  level_41  613 non-null    int64
 42  level_42  613 non-null    int64
 43  level_43  613 non-null    int64
 44  level_44  613 non-null    int64
 45  level_45  613 non-null    int64
 46  level_46  613 non-null    int64
 47  level_47  613 non-null    int64
 48  level_48  613 non-null    int64
 49  level_49  613 non-null    int64
 50  level_50  613 non-null    int64
 51  target    613 non-null    float64
dtypes: float64(1), int64(51)
memory usage: 253.8 KB

In [88]:
new_df.describe()

,level_0,level_1,level_2,level_3,level_4,level_5,level_6,level_7,level_8,level_9,...,level_42,level_43,level_44,level_45,level_46,level_47,level_48,level_49,level_50,target
count,613.000000,613.000000,613.000000,613.000000,613.000000,613.000000,613.000000,613.000000,613.000000,613.000000,...,613.000000,613.000000,613.000000,613.000000,613.000000,613.000000,613.000000,613.000000,613.000000,613.000000
mean,3.569331,4.574225,4.212072,4.308320,4.487765,4.420881,4.559543,4.334421,4.442088,4.257749,...,4.461664,4.654160,4.357259,4.492659,4.676998,4.450245,4.376835,4.226754,4.508972,43.450245
std,2.865248,2.770017,2.827396,2.870497,2.837989,2.858714,2.814841,2.834326,2.837999,2.807924,...,2.913331,2.777325,2.819389,2.836278,2.755875,2.843331,2.792951,2.780500,2.832238,29.703264
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,1.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,...,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,15.000000
50%,3.000000,5.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,...,5.000000,5.000000,4.000000,4.000000,5.000000,4.000000,4.000000,4.000000,4.000000,44.000000
75%,6.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,...,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,6.000000,7.000000,67.000000
max,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,...,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,99.000000

In [89]:
new_df.corr()

,level_0,level_1,level_2,level_3,level_4,level_5,level_6,level_7,level_8,level_9,...,level_42,level_43,level_44,level_45,level_46,level_47,level_48,level_49,level_50,target
level_0,1.000000,0.013093,-0.013920,0.046170,0.016833,0.042912,0.008655,-0.010002,-0.023167,0.007930,...,0.008394,-0.065358,0.013414,0.054903,0.027259,-0.002635,0.015413,-0.006796,0.033096,-0.047213
level_1,0.013093,1.000000,-0.024963,-0.061142,-0.020929,0.043508,-0.010889,0.014836,-0.043153,-0.024102,...,0.035736,0.005891,-0.028822,0.031318,0.013420,0.073963,0.046540,0.015314,0.067448,0.010397
level_2,-0.013920,-0.024963,1.000000,0.118969,-0.069930,-0.086264,-0.016371,0.005612,-0.040212,-0.039209,...,-0.040867,0.022672,-0.002756,0.017921,-0.038797,-0.066978,0.018004,0.036066,0.039755,-0.112603
level_3,0.046170,-0.061142,0.118969,1.000000,-0.085684,-0.007675,0.005914,-0.027556,-0.018765,-0.017782,...,0.014800,0.025899,-0.062896,-0.000625,0.041527,0.006988,0.007903,0.044659,-0.010692,0.045455
level_4,0.016833,-0.020929,-0.069930,-0.085684,1.000000,0.007483,-0.084334,0.009346,0.057579,-0.005755,...,-0.009691,0.068288,-0.005273,0.066115,-0.034560,-0.024223,-0.034978,-0.026256,-0.073830,0.015010
level_5,0.042912,0.043508,-0.086264,-0.007675,0.007483,1.000000,0.004394,-0.028290,-0.018742,0.023918,...,0.014105,-0.030001,0.006655,-0.043752,-0.022330,0.001575,-0.050185,-0.006887,0.018301,0.089708
level_6,0.008655,-0.010889,-0.016371,0.005914,-0.084334,0.004394,1.000000,0.019517,-0.000130,-0.044325,...,-0.026172,0.040051,-0.016994,-0.021486,-0.009312,0.005015,-0.018135,-0.036906,0.003366,-0.002901
level_7,-0.010002,0.014836,0.005612,-0.027556,0.009346,-0.028290,0.019517,1.000000,0.019373,-0.048215,...,0.032128,0.024887,-0.019065,-0.061383,-0.028614,-0.004116,0.048455,-0.014821,0.002577,0.022295
level_8,-0.023167,-0.043153,-0.040212,-0.018765,0.057579,-0.018742,-0.000130,0.019373,1.000000,0.049857,...,-0.056741,0.096339,-0.062043,0.053081,-0.002604,-0.004661,-0.043934,0.047532,0.040264,-0.024210
level_9,0.007930,-0.024102,-0.039209,-0.017782,-0.005755,0.023918,-0.044325,-0.048215,0.049857,1.000000,...,0.037164,-0.030666,0.013117,-0.045310,-0.008017,-0.007601,0.010097,-0.042867,0.052307,0.054167
level_10,-0.035597,-0.024548,-0.044409,0.131331,0.025115,-0.004037,-0.051491,0.010119,0.062619,-0.024031,...,0.001376,0.006684,-0.080685,-0.025707,0.026157,0.032842,-0.021754,0.005444,0.016210,-0.026716
level_11,-0.082190,0.044265,0.033711,-0.042079,0.070495,0.009130,-0.009471,0.042217,0.036657,-0.100675,...,-0.003987,0.050441,-0.046734,-0.024490,0.053958,0.016454,0.035003,0.010585,-0.066575,-0.030943
level_12,0.009161,-0.075940,-0.029201,-0.038757,-0.023176,0.036777,0.029517,0.034432,-0.045178,-0.027887,...,0.015787,-0.059090,0.049987,0.014762,0.009398,-0.015319,-0.031035,0.012338,-0.008677,-0.039561
level_13,0.007565,0.049177,0.084428,-0.019708,0.045682,-0.002165,0.019022,0.007254,-0.045218,0.020586,...,0.000382,-0.011710,-0.028698,-0.016467,-0.016442,-0.016530,0.040634,-0.073540,-0.012508,-0.071923
level_14,-0.010044,0.014058,0.077732,0.018581,0.025839,-0.025315,-0.007373,-0.002914,0.007681,0.041460,...,-0.007247,0.050556,-0.043560,-0.041759,0.026389,-0.008187,-0.052173,-0.060648,0.004450,-0.022662
level_15,0.008265,-0.021648,-0.056668,-0.066662,-0.079580,0.035241,0.028250,-0.010883,0.034323,0.006945,...,0.018058,-0.073860,0.054484,-0.023675,0.039162,-0.015241,0.036503,0.058101,0.021802,-0.026782
level_16,-0.038847,-0.030532,-0.002183,-0.047268,-0.026749,-0.072124,-0.000644,-0.017603,-0.042037,0.023364,...,0.070787,0.004092,0.012050,0.007483,0.065255,-0.005521,-0.040628,-0.039132,0.018908,-0.050841
level_17,-0.024542,-0.017291,-0.042748,-0.026369,-0.016789,-0.044427,0.070310,0.086192,-0.017938,-0.012151,...,-0.001415,0.047746,-0.017030,-0.051616,0.019887,-0.058932,-0.016217,-0.004056,-0.082686,-0.011282
level_18,0.016416,0.053051,0.009585,0.020588,-0.007702,-0.039093,-0.019593,0.051831,-0.052246,0.036476,...,0.019451,0.000522,0.039892,-0.031525,-0.062027,-0.016542,0.004701,-0.003524,0.013864,0.045930
level_19,-0.023584,-0.012299,0.013750,0.051156,0.021816,-0.045734,-0.012976,0.027304,0.004825,0.014962,...,0.004278,0.016899,-0.017768,0.057287,-0.023502,-0.060505,0.009669,-0.023035,0.019731,-0.001125
level_20,0.048711,0.019450,0.010725,0.046592,0.025173,0.058015,-0.036593,-0.029664,-0.019204,0.032491,...,-0.052508,-0.021330,-0.025238,-0.050486,0.053989,-0.037179,0.037672,-0.004469,-0.056968,0.076081
level_21,0.025526,-0.028527,-0.038431,0.019629,0.056527,-0.059883,0.016002,-0.031397,0.006862,-0.032766,...,-0.000021,0.002026,-0.026355,0.007195,-0.002489,-0.027308,-0.088245,0.015686,0.033945,-0.063435
level_22,0.005905,0.008468,-0.001373,-0.001018,0.047308,0.024429,-0.084359,0.087885,-0.025379,0.024137,...,0.006183,-0.028563,-0.100264,-0.026185,-0.057184,-0.004780,0.010477,-0.032093,-0.045183,0.010355
level_23,0.004257,0.037487,-0.080596,-0.006735,-0.062182,0.040867,0.048322,-0.018095,0.000673,-0.001328,...,-0.064297,0.070860,-0.041825,0.012912,-0.010479,0.025573,-0.034184,-0.028008,-0.023654,0.029551
level_24,-0.049474,-0.030515,-0.005523,0.033224,-0.067140,-0.040976,-0.020056,0.078871,0.062732,0.140282,...,0.001150,0.024089,0.044498,0.056079,0.017213,-0.024280,0.050354,-0.008591,-0.021457,-0.020304
level_25,0.013940,0.073808,0.010513,-0.025325,0.000136,-0.035681,-0.064929,-0.005462,-0.010899,0.023632,...,0.074560,0.006796,0.032113,-0.090751,-0.001185,-0.033956,-0.014919,0.073908,0.013552,0.066422
level_26,0.034747,-0.006558,-0.026968,0.061413,-0.008538,0.079824,0.004341,0.047402,0.008939,-0.006097,...,0.000050,-0.012408,-0.012763,-0.051847,0.044253,0.004313,0.017624,0.076721,-0.032182,0.022624
level_27,-0.043628,-0.053019,0.015237,-0.005821,0.020160,0.024344,-0.008839,-0.051385,0.003657,0.024110,...,-0.034079,0.055557,0.014947,-0.047394,0.015803,-0.089580,-0.041514,0.018955,0.114958,0.060302
level_28,-0.016753,0.043577,0.013343,0.095763,0.026393,-0.046427,-0.036920,0.013228,0.095479,0.063592,...,0.043229,0.025307,0.025769,0.001441,0.011052,0.021183,0.001337,0.110458,0.029675,-0.018999
level_29,0.048220,-0.053152,-0.017257,0.057791,-0.031684,-0.021610,0.075812,0.080369,0.032341,0.019258,...,0.039054,-0.034613,-0.019533,-0.029764,-0.012778,0.029303,0.016562,-0.031051,0.042565,0.028624
level_30,0.010266,0.062768,0.005624,-0.002073,-0.029971,0.041028,-0.018829,0.066592,0.014179,0.072858,...,-0.037770,0.023474,0.026263,-0.032913,0.007492,-0.019625,-0.028306,0.033801,-0.057235,-0.053969
level_31,0.043823,0.006557,0.047642,0.042661,-0.017189,0.003794,-0.033574,0.020785,0.003144,0.010303,...,-0.016733,-0.059540,-0.042005,-0.010279,0.078293,-0.013329,0.020946,0.010355,-0.022953,0.030413
level_32,0.098960,0.053114,0.013563,0.063331,0.033726,-0.024057,-0.029430,-0.026739,-0.011569,0.042206,...,0.026313,-0.007442,-0.034166,0.052879,0.032965,-0.049804,0.022852,-0.055193,0.031410,-0.021420
level_33,0.000578,0.019842,-0.056884,-0.090916,0.023781,0.011990,0.014362,-0.081267,0.009292,-0.019376,...,-0.040178,-0.051277,-0.082967,-0.068739,-0.007020,0.019283,-0.032621,-0.045059,-0.009842,-0.007274
level_34,-0.037934,0.012229,0.007655,-0.027144,0.029896,-0.007133,-0.039623,0.034708,0.021172,0.003204,...,-0.028580,-0.003611,0.080637,0.005379,-0.006464,0.037553,-0.057394,-0.033247,0.027626,0.002808
level_35,-0.053127,0.007285,-0.110326,0.029139,-0.019759,0.075230,-0.015914,-0.046228,-0.033881,0.133319,...,0.018264,-0.027056,0.000170,-0.062085,-0.029135,0.068393,0.061735,-0.031967,0.006478,-0.024917
level_36,0.063490,-0.024844,-0.038233,0.089523,-0.039052,0.064073,0.003132,-0.064804,-0.042460,-0.003009,...,0.021526,-0.019551,0.036024,0.040722,0.024250,0.020360,0.039152,-0.007776,0.077237,-0.023047
level_37,0.044873,0.016729,-0.024603,-0.005135,-0.050269,0.052769,-0.010449,-0.008316,0.017962,0.017106,...,0.027399,-0.088063,-0.016446,-0.055171,-0.055713,-0.004898,-0.006473,-0.026010,-0.011386,0.014918
level_38,-0.086350,-0.045583,0.001477,0.001817,-0.001172,-0.023044,-0.011992,0.014024,-0.015500,0.021517,...,0.008798,0.028682,-0.032940,-0.049420,-0.014190,0.002902,-0.018244,-0.031769,-0.075775,0.009954
level_39,0.039021,0.006569,0.015955,-0.030084,0.017501,0.012115,0.015082,0.048301,0.044027,0.029596,...,-0.051614,0.038188,-0.023151,0.001082,0.009310,-0.026595,0.042716,-0.093736,0.037227,-0.023997
level_40,0.044451,0.042925,-0.000464,0.000109,0.041835,-0.000284,-0.066199,0.049876,0.063722,0.052229,...,-0.049629,0.002227,0.018562,-0.028514,0.033047,0.014366,0.075470,-0.031481,0.061269,0.010110
level_41,-0.033491,0.041421,-0.022714,0.020530,0.040586,-0.038615,-0.032452,-0.025837,-0.008161,-0.031715,...,-0.056326,0.030648,0.000318,-0.016399,0.018874,-0.016842,0.004529,-0.055872,-0.024213,-0.024077
level_42,0.008394,0.035736,-0.040867,0.014800,-0.009691,0.014105,-0.026172,0.032128,-0.056741,0.037164,...,1.000000,-0.032943,0.017883,-0.044577,0.052591,0.010175,0.081803,0.032240,0.003755,-0.001122
level_43,-0.065358,0.005891,0.022672,0.025899,0.068288,-0.030001,0.040051,0.024887,0.096339,-0.030666,...,-0.032943,1.000000,-0.033234,-0.024800,0.088707,0.051409,-0.035412,-0.028973,0.045056,-0.014648
level_44,0.013414,-0.028822,-0.002756,-0.062896,-0.005273,0.006655,-0.016994,-0.019065,-0.062043,0.013117,...,0.017883,-0.033234,1.000000,0.013713,-0.014355,0.006807,-0.076886,0.060100,-0.078877,-0.012128
level_45,0.054903,0.031318,0.017921,-0.000625,0.066115,-0.043752,-0.021486,-0.061383,0.053081,-0.045310,...,-0.044577,-0.024800,0.013713,1.000000,0.004086,-0.037479,-0.036882,-0.069095,0.049487,-0.053453
level_46,0.027259,0.013420,-0.038797,0.041527,-0.034560,-0.022330,-0.009312,-0.028614,-0.002604,-0.008017,...,0.052591,0.088707,-0.014355,0.004086,1.000000,-0.003305,-0.043813,0.050729,-0.018260,-0.079822
level_47,-0.002635,0.073963,-0.066978,0.006988,-0.024223,0.001575,0.005015,-0.004116,-0.004661,-0.007601,...,0.010175,0.051409,0.006807,-0.037479,-0.003305,1.000000,-0.001236,-0.055098,-0.008416,-0.071435
level_48,0.015413,0.046540,0.018004,0.007903,-0.034978,-0.050185,-0.018135,0.048455,-0.043934,0.010097,...,0.081803,-0.035412,-0.076886,-0.036882,-0.043813,-0.001236,1.000000,0.008968,0.029214,0.009198
level_49,-0.006796,0.015314,0.036066,0.044659,-0.026256,-0.006887,-0.036906,-0.014821,0.047532,-0.042867,...,0.032240,-0.028973,0.060100,-0.069095,0.050729,-0.055098,0.008968,1.000000,-0.038748,0.043178
level_50,0.033096,0.067448,0.039755,-0.010692,-0.073830,0.018301,0.003366,0.002577,0.040264,0.052307,...,0.003755,0.045056,-0.078877,0.049487,-0.018260,-0.008416,0.029214,-0.038748,1.000000,0.004769
target,-0.047213,0.010397,-0.112603,0.045455,0.015010,0.089708,-0.002901,0.022295,-0.024210,0.054167,...,-0.001122,-0.014648,-0.012128,-0.053453,-0.079822,-0.071435,0.009198,0.043178,0.004769,1.000000

In [90]:
u1 = np.mean(df,axis=0)

In [92]:
df - u1

,level_0,level_1,level_2,level_3,level_4,level_5,level_6,level_7,level_8,level_9,...,level_42,level_43,level_44,level_45,level_46,level_47,level_48,level_49,level_50,target
0,0.4,-0.3,2.1,0.0,-1.4,-2.6,2.7,2.7,-5.1,-3.4,...,-1.4,2.0,0.6,1.5,1.6,-1.2,1.2,0.8,-3.5,-8.333333
1,5.4,-3.3,-2.9,1.0,1.6,0.4,-4.3,1.7,-3.1,1.6,...,0.6,-2.0,-3.4,-3.5,-3.4,-1.2,4.2,0.8,-2.5,NaN
2,-2.6,1.7,4.1,-4.0,-1.4,3.4,-2.3,4.7,3.9,-0.4,...,2.6,-1.0,0.6,0.5,0.6,-0.2,0.2,-2.2,3.5,3.666667
3,-2.6,-1.3,3.1,2.0,-1.4,2.4,3.7,-4.3,-1.1,1.6,...,0.6,4.0,-2.4,-3.5,-1.4,5.8,4.2,1.8,1.5,NaN
4,-3.6,-0.3,-0.9,2.0,2.6,3.4,-3.3,0.7,2.9,1.6,...,-1.4,-3.0,0.6,3.5,-0.4,-2.2,-2.8,2.8,1.5,4.666667
5,1.4,-3.3,-3.9,3.0,0.6,-4.6,-1.3,-4.3,1.9,2.6,...,-4.4,2.0,-1.4,3.5,-2.4,3.8,-3.8,-4.2,-0.5,21.666667
6,4.4,3.7,-3.9,0.0,2.6,4.4,4.7,3.7,-2.1,0.6,...,1.6,-1.0,1.6,-1.5,3.6,-2.2,-0.8,-1.2,4.5,15.666667
7,-2.6,-0.3,-0.9,-1.0,1.6,-3.6,-0.3,1.7,1.9,3.6,...,4.6,-3.0,-0.4,-1.5,2.6,-0.2,-1.8,0.8,-4.5,-37.333333
8,-0.6,5.7,0.1,1.0,1.6,-2.6,-3.3,-3.3,-2.1,-3.4,...,-1.4,0.0,3.6,-0.5,0.6,-1.2,3.2,-3.2,-0.5,NaN
9,0.4,-2.3,3.1,-4.0,-6.4,-0.6,3.7,-3.3,2.9,-4.4,...,-1.4,2.0,0.6,1.5,-1.4,-1.2,-3.8,3.8,0.5,NaN

In [93]:
u1

level_0      3.600000
level_1      3.300000
level_2      4.900000
level_3      4.000000
level_4      6.400000
level_5      4.600000
level_6      4.300000
level_7      4.300000
level_8      5.100000
level_9      4.400000
level_10     5.200000
level_11     4.500000
level_12     3.200000
level_13     3.500000
level_14     7.400000
level_15     3.900000
level_16     5.100000
level_17     5.500000
level_18     5.000000
level_19     4.100000
level_20     3.500000
level_21     5.000000
level_22     6.100000
level_23     2.900000
level_24     5.600000
level_25     3.900000
level_26     5.100000
level_27     4.400000
level_28     3.200000
level_29     2.700000
level_30     4.400000
level_31     4.900000
level_32     3.600000
level_33     4.500000
level_34     5.000000
level_35     4.000000
level_36     5.500000
level_37     3.700000
level_38     6.600000
level_39     4.000000
level_40     3.300000
level_41     5.000000
level_42     4.400000
level_43     4.000000
level_44     4.400000
level_45     5.500000
level_46     5.400000
level_47     3.200000
level_48     4.800000
level_49     4.200000
level_50     4.500000
target      39.333333
dtype: float64

In [96]:
sum =3.6
l = []
for u in df['level_0']:
    l.append(u-sum)

In [97]:
l

[0.3999999999999999,
 5.4,
 -2.6,
 -2.6,
 -3.6,
 1.4,
 4.4,
 -2.6,
 -0.6000000000000001,
 0.3999999999999999]

In [98]:
Xc = new_df - np.mean(new_df,axis=0)

In [99]:
Xc

,level_0,level_1,level_2,level_3,level_4,level_5,level_6,level_7,level_8,level_9,...,level_42,level_43,level_44,level_45,level_46,level_47,level_48,level_49,level_50,target
0,0.430669,-1.574225,2.787928,-0.30832,0.512235,-2.420881,2.440457,2.665579,-4.442088,-3.257749,...,-1.461664,1.34584,0.642741,2.507341,2.323002,-2.450245,1.623165,0.773246,-3.508972,-12.450245
2,-2.569331,0.425775,4.787928,-4.30832,0.512235,3.579119,-2.559543,4.665579,4.557912,-0.257749,...,2.538336,-1.65416,0.642741,1.507341,1.323002,-1.450245,0.623165,-2.226754,3.491028,-0.450245
4,-3.569331,-1.574225,-0.212072,1.69168,4.512235,3.579119,-3.559543,0.665579,3.557912,1.742251,...,-1.461664,-3.65416,0.642741,4.507341,0.323002,-3.450245,-2.376835,2.773246,1.491028,0.549755
5,1.430669,-4.574225,-3.212072,2.69168,2.512235,-4.420881,-1.559543,-4.334421,2.557912,2.742251,...,-4.461664,1.34584,-1.357259,4.507341,-1.676998,2.549755,-3.376835,-4.226754,-0.508972,17.549755
6,4.430669,2.425775,-3.212072,-0.30832,4.512235,4.579119,4.440457,3.665579,-1.442088,0.742251,...,1.538336,-1.65416,1.642741,-0.492659,4.323002,-3.450245,-0.376835,-1.226754,4.491028,11.549755
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,4.430669,-3.574225,1.787928,0.69168,-1.487765,4.579119,-0.559543,-1.334421,2.557912,-2.257749,...,-2.461664,-0.65416,4.642741,-2.492659,-3.676998,2.549755,0.623165,1.773246,3.491028,-39.450245
995,-2.569331,-3.574225,-2.212072,-4.30832,-4.487765,-1.420881,0.440457,-3.334421,4.557912,1.742251,...,-4.461664,-2.65416,2.642741,2.507341,0.323002,-0.450245,-4.376835,3.773246,-1.508972,-26.450245
996,3.430669,3.425775,2.787928,1.69168,-0.487765,2.579119,-3.559543,-3.334421,-1.442088,1.742251,...,1.538336,3.34584,4.642741,-1.492659,2.323002,3.549755,4.623165,-2.226754,-0.508972,29.549755
997,4.430669,-2.574225,-4.212072,-2.30832,1.512235,-4.420881,-3.559543,-2.334421,-2.442088,2.742251,...,-2.461664,-3.65416,2.642741,1.507341,-4.676998,-2.450245,3.623165,1.773246,-0.508972,25.549755
998,4.430669,0.425775,-2.212072,-1.30832,-1.487765,2.579119,-1.559543,0.665579,-4.442088,-0.257749,...,1.538336,-0.65416,4.642741,4.507341,-3.676998,-0.450245,0.623165,-3.226754,4.491028,-28.450245

In [100]:
Xc.drop(columns ='target',inplace=True)

In [101]:
Xc

,level_0,level_1,level_2,level_3,level_4,level_5,level_6,level_7,level_8,level_9,...,level_41,level_42,level_43,level_44,level_45,level_46,level_47,level_48,level_49,level_50
0,0.430669,-1.574225,2.787928,-0.30832,0.512235,-2.420881,2.440457,2.665579,-4.442088,-3.257749,...,0.513866,-1.461664,1.34584,0.642741,2.507341,2.323002,-2.450245,1.623165,0.773246,-3.508972
2,-2.569331,0.425775,4.787928,-4.30832,0.512235,3.579119,-2.559543,4.665579,4.557912,-0.257749,...,0.513866,2.538336,-1.65416,0.642741,1.507341,1.323002,-1.450245,0.623165,-2.226754,3.491028
4,-3.569331,-1.574225,-0.212072,1.69168,4.512235,3.579119,-3.559543,0.665579,3.557912,1.742251,...,-1.486134,-1.461664,-3.65416,0.642741,4.507341,0.323002,-3.450245,-2.376835,2.773246,1.491028
5,1.430669,-4.574225,-3.212072,2.69168,2.512235,-4.420881,-1.559543,-4.334421,2.557912,2.742251,...,3.513866,-4.461664,1.34584,-1.357259,4.507341,-1.676998,2.549755,-3.376835,-4.226754,-0.508972
6,4.430669,2.425775,-3.212072,-0.30832,4.512235,4.579119,4.440457,3.665579,-1.442088,0.742251,...,-4.486134,1.538336,-1.65416,1.642741,-0.492659,4.323002,-3.450245,-0.376835,-1.226754,4.491028
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,4.430669,-3.574225,1.787928,0.69168,-1.487765,4.579119,-0.559543,-1.334421,2.557912,-2.257749,...,-0.486134,-2.461664,-0.65416,4.642741,-2.492659,-3.676998,2.549755,0.623165,1.773246,3.491028
995,-2.569331,-3.574225,-2.212072,-4.30832,-4.487765,-1.420881,0.440457,-3.334421,4.557912,1.742251,...,-3.486134,-4.461664,-2.65416,2.642741,2.507341,0.323002,-0.450245,-4.376835,3.773246,-1.508972
996,3.430669,3.425775,2.787928,1.69168,-0.487765,2.579119,-3.559543,-3.334421,-1.442088,1.742251,...,-4.486134,1.538336,3.34584,4.642741,-1.492659,2.323002,3.549755,4.623165,-2.226754,-0.508972
997,4.430669,-2.574225,-4.212072,-2.30832,1.512235,-4.420881,-3.559543,-2.334421,-2.442088,2.742251,...,1.513866,-2.461664,-3.65416,2.642741,1.507341,-4.676998,-2.450245,3.623165,1.773246,-0.508972
998,4.430669,0.425775,-2.212072,-1.30832,-1.487765,2.579119,-1.559543,0.665579,-4.442088,-0.257749,...,0.513866,1.538336,-0.65416,4.642741,4.507341,-3.676998,-0.450245,0.623165,-3.226754,4.491028

In [102]:
X_array = np.array(Xc)

In [103]:
X_array

array([[ 0.43066884, -1.57422512,  2.78792822, ...,  1.62316476,
         0.77324633, -3.50897227],
       [-2.56933116,  0.42577488,  4.78792822, ...,  0.62316476,
        -2.22675367,  3.49102773],
       [-3.56933116, -1.57422512, -0.21207178, ..., -2.37683524,
         2.77324633,  1.49102773],
       ...,
       [ 3.43066884,  3.42577488,  2.78792822, ...,  4.62316476,
        -2.22675367, -0.50897227],
       [ 4.43066884, -2.57422512, -4.21207178, ...,  3.62316476,
         1.77324633, -0.50897227],
       [ 4.43066884,  0.42577488, -2.21207178, ...,  0.62316476,
        -3.22675367,  4.49102773]])

In [104]:
X_array2 = Xc.to_numpy()

In [106]:
Cov = X_array.T@X_array

In [107]:
Cov

array([[5024.30342577,   63.5954323 ,  -69.01305057, ...,   75.48450245,
         -33.137031  ,  164.36867863],
       [  63.5954323 , 4695.87275693, -119.64926591, ...,  220.35399674,
          72.18270799,  323.84176183],
       [ -69.01305057, -119.64926591, 4892.43066884, ...,   87.01141925,
         173.52202284,  194.83360522],
       ...,
       [  75.48450245,  220.35399674,   87.01141925, ..., 4773.95106036,
          42.61990212,  141.4274062 ],
       [ -33.137031  ,   72.18270799,  173.52202284, ...,   42.61990212,
        4731.4812398 , -186.74714519],
       [ 164.36867863,  323.84176183,  194.83360522, ...,  141.4274062 ,
        -186.74714519, 4909.20065253]])

In [111]:
Cov = Cov/(X_array.shape[0]-1)

In [112]:
Cov

array([[ 8.20964612,  0.10391411, -0.11276642, ...,  0.12334069,
        -0.05414548,  0.26857627],
       [ 0.10391411,  7.6729947 , -0.19550534, ...,  0.36005555,
         0.1179456 ,  0.52915321],
       [-0.11276642, -0.19550534,  7.99416776, ...,  0.14217552,
         0.28353272,  0.31835556],
       ...,
       [ 0.12334069,  0.36005555,  0.14217552, ...,  7.80057363,
         0.06964036,  0.23109053],
       [-0.05414548,  0.1179456 ,  0.28353272, ...,  0.06964036,
         7.7311785 , -0.30514239],
       [ 0.26857627,  0.52915321,  0.31835556, ...,  0.23109053,
        -0.30514239,  8.02156969]])

In [113]:
eig_vals, eig_vecs = np.linalg.eig(Cov)

In [114]:
eig_vals

array([12.87378029, 12.50423098, 12.15187003, 11.90884311, 11.62928131,
       11.47568583, 11.11268822,  4.32912778, 10.90484609,  4.50772046,
       10.73291054, 10.56669361, 10.47307802,  4.71904863, 10.10889609,
        9.98930702,  9.74770175,  9.65995678,  9.60572542,  4.87767298,
        9.30452436,  9.12466772,  9.08364679,  8.92760197,  8.69774077,
        5.08179464,  5.25401085,  5.3660329 ,  5.46257267,  8.31300484,
        8.30860904,  8.10831179,  5.60975263,  5.74039908,  5.88828872,
        5.87594279,  6.01681792,  6.19073012,  6.2837251 ,  7.84407553,
        6.41098   ,  6.50199516,  6.64794103,  6.69855568,  7.70740389,
        7.56380653,  6.96888679,  7.44026642,  7.33516727,  7.22222068,
        7.14060308])

In [115]:
eig_vecs

array([[ 2.00477025e-01,  1.64364199e-03,  1.40116020e-01, ...,
        -5.58635898e-02, -4.19246815e-01, -5.23062444e-05],
       [ 1.18631471e-03, -5.61977869e-02, -2.67909117e-02, ...,
        -8.41161938e-02,  2.93233844e-01, -7.93466810e-02],
       [ 4.23255539e-02,  2.96611367e-01,  3.12847671e-03, ...,
         1.65399864e-01, -1.11993423e-01, -2.03958275e-02],
       ...,
       [ 1.65225968e-01, -3.48308007e-02,  4.26983097e-02, ...,
        -1.85463555e-01,  8.71082353e-02, -5.46705963e-02],
       [ 9.95646450e-02, -3.12790776e-03, -1.64818051e-01, ...,
        -5.43339975e-02, -2.38961901e-01, -1.06896278e-01],
       [ 1.04272099e-01,  1.54516860e-01,  1.04419503e-02, ...,
        -5.83190981e-02, -1.31038706e-01,  1.54744181e-01]])

In [116]:
indexes = np.argsort(eig_vals)[::-1]

In [117]:
indexes

array([ 0,  1,  2,  3,  4,  5,  6,  8, 10, 11, 12, 14, 15, 16, 17, 18, 20,
       21, 22, 23, 24, 29, 30, 31, 39, 44, 45, 47, 48, 49, 50, 46, 43, 42,
       41, 40, 38, 37, 36, 34, 35, 33, 32, 28, 27, 26, 25, 19, 13,  9,  7],
      dtype=int64)

In [118]:
sorted_eig = eig_vals[indexes]
sorted_eig_vecs = eig_vecs[:,indexes]

In [156]:
def variance_captured(eigen_vals,thresh):
    u = 0
    n = 0
    total = np.sum(eigen_vals)
    while((u/total)<thresh):
        u += eigen_vals[n]
        n += 1 
    return n-1

In [157]:
total = np.sum(eig_vals)

In [159]:
variance_captured(sorted_eig,0.90)

42

In [160]:
variance_captured(sorted_eig,0.80)

35

In [161]:
var_ratio = sorted_eig / total
cum_var_ratio = np.cumsum(var_ratio)


k = np.argmax(cum_var_ratio >= 0.80) + 1

In [162]:
k

36

We can drop atmost 15 features , but at the cost of losing 20% of information of data .

In [163]:
Selected_eig_vecs = sorted_eig_vecs[:,:k]

In [165]:
Selected_eig_vecs.shape

(51, 36)

In [166]:
X_reconstructed = np.dot(X_array,Selected_eig_vecs)

In [168]:
X_reconstructed.shape

(613, 36)

In [213]:
from sklearn.preprocessing import StandardScaler

In [216]:
def PCA(data_frame,thresh=None):
    mean = np.mean(data_frame,axis=0)
    
    Xc = StandardScaler().fit_transform(data_frame)

    Cov = np.cov(Xc,rowvar=False)
    Eig_vals,Eig_vecs = np.linalg.eig(Cov)
    indexes = np.argsort(Eig_vals)[::-1]
    sorted_eig_val = Eig_vals[indexes]
    sorted_eig_vec = Eig_vecs[:,indexes]
    print(sorted_eig_val)
    if thresh is None:
        thresh = 0.92
    total = np.sum(sorted_eig_val)
    cum_var = np.cumsum(sorted_eig_val) / total
    top_k = np.argmax(cum_var >= thresh) + 1

    print(top_k)
    final_eigs_vecs = sorted_eig_vec[:,:top_k]

    cols = [f'{i+1}th PC' for i in range(top_k)]
    
    Projected_data = np.dot(Xc,final_eigs_vecs)
    new_Data_frame = pd.DataFrame(Projected_data,columns=cols,index = data_frame.index)
    return new_Data_frame

In [203]:
Actual_data = pd.read_csv('breast-cancer.csv')

In [204]:
Actual_data.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [189]:
Actual_data.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst'],
      dtype='object')

In [190]:
P_data = Actual_data.drop(columns = ['id','diagnosis'])

In [192]:
P_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 30 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   radius_mean              569 non-null    float64
 1   texture_mean             569 non-null    float64
 2   perimeter_mean           569 non-null    float64
 3   area_mean                569 non-null    float64
 4   smoothness_mean          569 non-null    float64
 5   compactness_mean         569 non-null    float64
 6   concavity_mean           569 non-null    float64
 7   concave points_mean      569 non-null    float64
 8   symmetry_mean            569 non-null    float64
 9   fractal_dimension_mean   569 non-null    float64
 10  radius_se                569 non-null    float64
 11  texture_se               569 non-null    float64
 12  perimeter_se             569 non-null    float64
 13  area_se                  569 non-null    float64
 14  smoothness_se            569 non-null    float64
 15  compactness_se           569 non-null    float64
 16  concavity_se             569 non-null    float64
 17  concave points_se        569 non-null    float64
 18  symmetry_se              569 non-null    float64
 19  fractal_dimension_se     569 non-null    float64
 20  radius_worst             569 non-null    float64
 21  texture_worst            569 non-null    float64
 22  perimeter_worst          569 non-null    float64
 23  area_worst               569 non-null    float64
 24  smoothness_worst         569 non-null    float64
 25  compactness_worst        569 non-null    float64
 26  concavity_worst          569 non-null    float64
 27  concave points_worst     569 non-null    float64
 28  symmetry_worst           569 non-null    float64
 29  fractal_dimension_worst  569 non-null    float64
dtypes: float64(30)
memory usage: 133.5 KB

In [193]:
P_data.isnull().sum()

radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64

In [194]:
P_data.duplicated().sum()

0

In [217]:
n = PCA(P_data)

[1.33049908e+01 5.70137460e+00 2.82291016e+00 1.98412752e+00
 1.65163324e+00 1.20948224e+00 6.76408882e-01 4.77456255e-01
 4.17628782e-01 3.51310875e-01 2.94433153e-01 2.61621161e-01
 2.41782421e-01 1.57286149e-01 9.43006956e-02 8.00034045e-02
 5.95036135e-02 5.27114222e-02 4.95647002e-02 3.12142606e-02
 3.00256631e-02 2.74877113e-02 2.43836914e-02 1.80867940e-02
 1.55085271e-02 8.19203712e-03 6.91261258e-03 1.59213600e-03
 7.50121413e-04 1.33279057e-04]
8

In [218]:
n

,1th PC,2th PC,3th PC,4th PC,5th PC,6th PC,7th PC,8th PC
0,9.192837,1.948583,-1.123166,3.633731,1.195110,1.411424,-2.159370,0.398407
1,2.387802,-3.768172,-0.529293,1.118264,-0.621775,0.028656,-0.013358,-0.240988
2,5.733896,-1.075174,-0.551748,0.912083,0.177086,0.541452,0.668166,-0.097374
3,7.122953,10.275589,-3.232790,0.152547,2.960878,3.053422,-1.429911,-1.059565
4,3.935302,-1.948072,1.389767,2.940639,-0.546747,-1.226495,0.936213,-0.636376
...,...,...,...,...,...,...,...,...
564,6.439315,-3.576817,2.459487,1.177314,0.074824,-2.375193,0.596130,0.035471
565,3.793382,-3.584048,2.088476,-2.506028,0.510723,-0.246710,0.716326,1.113360
566,1.256179,-1.902297,0.562731,-2.089227,-1.809991,-0.534447,0.192758,-0.341887
567,10.374794,1.672010,-1.877029,-2.356031,0.033742,0.567936,-0.223082,0.280239
568,-5.475243,-0.670637,1.490443,-2.299157,0.184703,1.617837,-1.698952,-1.046354